### ISSUE TITLE
Retention limit doesn't seem to work

### ISSUE THREAD

**Issue by sdurrheimer** [cycloidio/ansible-backup-snapshot#1]
![Non-working use-case](https://pastefile-owl.cycloid.io/f1391a77093ba0147dfd871ec197c54a)

```
admin@bastion0:/etc/cron.d$ /usr/local/bin/ec2snap --verbosity ERROR --ignore-in-use-snapshot  -t project 'the-hive' -t role 'queue' -u  -g 2 w -r eu-west-3 -c /home/admin/.aws/credentials --add_tags backup:true
Traceback (most recent call last):
  File "/usr/local/bin/ec2snap", line 726, in <module>
    main()
  File "/usr/local/bin/ec2snap", line 716, in main
    num_mk_err, num_rm_err = selected_instances.mk_rm_snapshot()
  File "/usr/local/bin/ec2snap", line 482, in mk_rm_snapshot
    if not self._remove_old_snap(iid):
  File "/usr/local/bin/ec2snap", line 510, in _remove_old_snap
    '%Y-%m-%dT%H:%M:%S.000Z')
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2019-06-25T10:01:46.574Z' does not match format '%Y-%m-%dT%H:%M:%S.000Z'
```

**Comment by gaelL** [comment]
This should be fixed by last ec2snap version 5.4
